# Generated by Django 6.0.4 on 2026-05-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('manager_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('manager_contact', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('warehouse_type', models.CharField(choices=[('GENERAL', 'General'), ('COLD', 'Cold Storage'), ('FULFILLMENT', 'Fulfillment')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='warehouse_w_name_690490_idx'), models.Index(fields=['location'], name='warehouse_w_locatio_c848ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_code', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehouse.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'rack_code')},
            },
        ),
    ]
